array-manipulation-3 | Cristofer Martinez
CristoferMar/c0521-code-solutions pull request #60
Opened 2021-05-23 07:01 UTC by CristoferMar

![array-manipulation-3](https://user-images.githubusercontent.com/82407007/119251168-f0b7e880-bb59-11eb-8d77-877108912d75.png)

2021-06-07 18:33 UTC, codingcodymiller requested changes
Great start on this! Some notes for you:

2021-06-07 18:33 UTC, codingcodymiller commented on array-manipulation-3/src/difference.js
> +    var post = 1;
This would be better as a Boolean

2021-06-07 18:33 UTC, codingcodymiller commented on array-manipulation-3/src/unique.js
> +  var Unique = [array[0]];
You should avoid capital letters at the beginning of variables, that sort of casing is meant to be preserved for Constructor Functions

2021-06-07 18:33 UTC, codingcodymiller commented on array-manipulation-3/src/union.js
> +    var push = 1;
This would be better as a Boolean

2021-06-07 18:33 UTC, codingcodymiller commented on array-manipulation-3/src/unique.js
> +    var post = 1;
This would be better as a Boolean

2021-06-29 18:20 UTC, thebearingedge approved these changes

2021-06-29 22:33 UTC, merged